# Generated by Django 3.2.4 on 2023-06-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='test', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='long',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='place_id',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
