# Generated by Django 3.2.4 on 2023-09-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20230830_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=14),
        ),
        migrations.AlterField(
            model_name='event',
            name='long',
            field=models.DecimalField(decimal_places=10, max_digits=14),
        ),
    ]
