# Generated by Django 3.2.4 on 2023-11-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20231130_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='title',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmainimage',
            name='title',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
