# Generated by Django 3.2.4 on 2023-12-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20231130_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmainimage',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='main_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.eventmainimage'),
        ),
    ]
