# Generated by Django 3.2.4 on 2023-12-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20231207_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmainimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
