# Generated by Django 3.2.4 on 2024-08-27 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0012_eventfavourite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventfavourite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='eventfavourite',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventfavourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventfavourite',
            unique_together={('user', 'event')},
        ),
    ]
