# Generated by Django 3.2.4 on 2024-09-05 18:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0013_auto_20240827_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventGuest',
            new_name='EventAttendee',
        ),
    ]
