# Generated by Django 3.2.4 on 2024-09-05 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_rename_eventguest_eventattendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
