# Generated by Django 3.2.4 on 2024-09-07 16:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0016_auto_20240905_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventattendee',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together={('user', 'event')},
        ),
    ]
